# DataSync Configuration
# 精简配置，专注于核心功能

database:
  remote:
    host: ${REMOTE_DB_HOST:-localhost}
    port: ${REMOTE_DB_PORT:-5432}
    name: ${REMOTE_DB_NAME:-cryptodb}
    user: ${REMOTE_DB_USER:-postgres}
    password: ${REMOTE_DB_PASSWORD:-2450512223}
    ssl_mode: require
    pool_size: 10
    timeout: 30

  local:
    host: localhost
    port: 5432
    name: cryptodb
    user: postgres
    password: 2450512223
    pool_size: 20

# 同步配置
sync:
  interval_minutes: 3        # 同步间隔（分钟）
  batch_size: 5000          # 批量查询大小
  retry_max: 3              # 最大重试次数

# 数据迁移配置
migration:
  enabled: true
  hot_retention_days: 182    # 热数据保留6个月
  warm_retention_days: 1460  # 温数据保留4年
  batch_size: 5000          # 每批迁移记录数

# 远程清理配置
cleanup:
  enabled: true
  retention_days: 60        # 远程数据保留2个月
  batch_size: 5000         # 每批清理记录数
  max_delete_per_day: 50000  # 每天最大删除数量限制

# 监控配置
monitoring:
  enabled: true
  service_name: "datasync"
  monitor_url: "http://localhost:9527"
  timeout: 5
  retry_count: 2

# 日志配置
logging:
  level: INFO
  format: json
  file: /var/log/databao/datasync.log
  rotate_days: 30